version: '3'

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - influxdb_network

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=meu_banco_de_dados
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    networks:
      - influxdb_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4000:3000"
    depends_on:
      - influxdb
    networks:
      - influxdb_network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    volumes:
      - ./config/mosquitto/config:/mosquitto/config
      - ./config/mosquitto/data:/mosquitto/data
      - ./config/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
    networks:
      - influxdb_network

networks:
  influxdb_network:
