version: '3'

services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=Dados dos Sensores
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_USER=admin
      - INFLUXDB_USER_PASSWORD=admin123

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - influxdb

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb


  